# Appium Java TestNG Framework Config Template

base.url=${BASE_URL}
environment=qa
test.role=Admin
testng.groups=smoke,regression

platformName=${PLATFORM_NAME}
android.app=${ANDROID_APP_PATH}
android.appPackage=${ANDROID_APP_PACKAGE}
android.appActivity=${ANDROID_APP_ACTIVITY}
ios.app=${IOS_APP_PATH}
ios.bundleId=${IOS_BUNDLE_ID}
