# Selenium Python PyTest Framework Config Template

project: selenium-python-pytest
base_url: ${BASE_URL}
browser: chrome
headless: false
default_role: Admin
default_suite: smoke
run_command: "pytest -m smoke --browser chrome"
